// List of barangays in Calamba City
const barangays = [
    "BAGONG KALSADA",
    "BANADERO",
    "BANLIC",
    "BARANDAL",
    "BARANGAY 1",
    "BARANGAY 2",
    "BARANGAY 3",
    "BARANGAY 4",
    "BARANGAY 5",
    "BARANGAY 6",
    "BARANGAY 7",
    "BATINO",
    "BUBUYAN",
    "BUCAL",
    "BUNGGO",
    "BUROL",
    "CAMALIGAN",
    "CANLUBANG",
    "HALANG",
    "HORNALAN",
    "KAY-ANLOG",
    "LAMESA",
    "LAGUERTA",
    "LAWA",
    "LECHERIA",
    "LINGGA",
    "LOOC",
    "MABATO",
    "MAJADA OUT",
    "MAKILING",
    "MAPAGONG",
    "MASILI",
    "MAUNONG",
    "MAYAPA",
    "MILAGROSA",
    "PACIANO RIZAL",
    "PALINGON",
    "PALO-ALTO",
    "PANSOL",
    "PARIAN",
    "PRINZA",
    "PUNTA",
    "PUTING LUPA",
    "REAL",
    "SAIMSIM",
    "SAMPIRUHAN",
    "SAN CRISTOBAL",
    "SAN JOSE",
    "SAN JUAN",
    "SIRANG LUPA",
    "SUCOL",
    "TURBINA",
    "ULANGO",
    "UWISAN"
];

export default barangays;