const commodities = [
    "ALUGBATI",
    "AMPALAYA",
    "BAGUIO BEANS",
    "BAWANG",
    "KALABASA",
    "KAMATIS",
    "KAMOTE",
    "KANGKONG",
    "LABANOS",
    "LUYA",
    "MANI",
    "MUNGGO",
    "MUSTASA",
    "OKRA",
    "PAAYAP",
    "PAKWAN",
    "PAMINTA",
    "PATANI",
    "PATOLA",
    "PECHAY",
    "PINYA",
    "PIPINO",
    "SALAY",
    "SALUYOT",
    "SIGARILYAS",
    "SILING LABUYO",
    "SILING PANIGANG",
    "SILING TINGALA",
    "SITAO",
    "TALONG",
    "TUBO",
    "UBE",
    "UPO",
    "BUNGULAN",
    "LACATAN",
    "LAGKITAN",
    "LATUNDAN",
    "SABA",
    "SENORITA",
    "LIBERICA",
    "ROBUSTA",
    "AVOCADO",
    "BARIBA",
    "CACAO",
    "CALAMANSI",
    "CHICO",
    "CITRUS",
    "DALANGHITA",
    "DRAGON FRUIT",
    "DURIAN",
    "GYABANO",
    "JACKFRUIT",
    "LANZONES",
    "MANGO",
    "PAPAYA",
    "POMELO",
    "RAMBUTAN",
    "SANTOL"
];

export default commodities;