// List of industrial crops 
const indusCrops = [
    "ALUGBATI",
    "AMPALAYA",
    "BAGUIO BEANS",
    "BAWANG",
    "KALABASA",
    "KAMATIS",
    "KAMOTE",
    "KANGKONG",
    "LABANOS",
    "LUYA",
    "MANI",
    "MUNGGO",
    "MUSTASA",
    "OKRA",
    "PAAYAP",
    "PAKWAN",
    "PAMINTA",
    "PATANI",
    "PATOLA",
    "PECHAY",
    "PINYA",
    "PIPINO",
    "SALAY",
    "SALUYOT",
    "SIGARILYAS",
    "SILING LABUYO",
    "SILING PANIGANG",
    "SILING TINGALA",
    "SITAO",
    "TALONG",
    "TUBO",
    "UBE",
    "UPO"
];